#!/bin/sh

set -e

cd "$(dirname "$0")"

log() {
  >&2 echo "[$(date -Iseconds) watch] $*"
}



log "starting"

while true
do
	for watcher in ./watcher/*
  do
		log "running $watcher"
		(exec $watcher)
	done

	log "sleeping for 5 min"

	sleep 5m
done
