#!/bin/sh

set -e

ref='./.refs/callisto'

latest() {
    curl -s "https://github.com/callisto-lang/compiler/commits/main.atom" \
        | xq -re .feed.entry[0].id \
        | xargs basename
}

rebuild() {
    gh workflow run build-and-docker-release.yml \
        -R booniepepper/callisto-docker
}

prev=$(cat "$ref" || echo "init")
curr=$(latest)

if [ "$curr" != "$prev" ]
then
    mkdir -p .refs
    echo "$curr" > "$ref"
    rebuild
fi
