#!/bin/sh

set -e

ref='./.refs/nova-rust'

latest() {
    curl -s "https://git.casuallyblue.dev/vega/nova-rust.rss" \
        | xq -re .rss.channel.item[0].guid.'"#text"'
}

rebuild() {
    gh workflow run build-and-docker-release.yml \
        -R booniepepper/nova-rust-docker
}

prev=$(cat "$ref" || echo "init")
curr=$(latest)

if [ "$curr" != "$prev" ]
then
    mkdir -p .refs
    echo "$curr" > "$ref"
    rebuild
fi
